replicaCount: 2
image:
  repository: <your_dockerhub_username>/myapp
  tag: latest
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  host: myapp.local
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"
config:
  flaskEnv: production
  appName: My Flask App
secret:
  apiKey: YXBpLWtleS1leGFtcGxlCg==