apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  DB_HOST: cG9zdGdyZXM=               # "postgres" (base64)
  DB_NAME: bXlkYg==                   # "mydb"
  DB_USER: YWRtaW4=                   # "admin"
  DB_PASSWORD: cGFzc3dvcmQ=           # "password"