apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
#      imagePullSecrets:
#      - name: dockerhub-secret
      containers:
      - name: myapp
        image: truongloc2002/myapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
          - name: FLASK_ENV
            valueFrom:
              configMapKeyRef:
                name: myapp-config
                key: FLASK_ENV
          - name: APP_NAME
            valueFrom:
              configMapKeyRef:
                name: myapp-config
                key: APP_NAME
          - name: API_KEY
            valueFrom:
              secretKeyRef:
                name: myapp-secret
                key: API_KEY
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: DB_HOST
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: DB_NAME
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: DB_PASSWORD
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5