name: CI/CD for Minikube
on:
 push:
   branches:
     - main
jobs:
 build-and-deploy:
   runs-on: ubuntu-latest
   steps:
   - name: Checkout code
     uses: actions/checkout@v3
   - name: Set up Docker Buildx
     uses: docker/setup-buildx-action@v2
   - name: Login to Docker Hub
     uses: docker/login-action@v2
     with:
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}
   - name: Build and push Docker image
     uses: docker/build-push-action@v4
     with:
       context: .
       push: true
       tags: ${{ secrets.DOCKER_USERNAME }}/myapp:latest
   - name: Start Minikube
     run: |
       minikube start
   - name: Configure Docker Hub credentials in Minikube
     run: |
       kubectl create secret docker-registry dockerhub-secret \
         --docker-username=${{ secrets.DOCKERHUB_USERNAME }} \
         --docker-password=${{ secrets.DOCKERHUB_TOKEN }} \
         --docker-email=truonglocnguyenkhanh@gmail.com --dry-run=client -o yaml | kubectl apply -f -
   - name: Deploy to Minikube
     run: |
       kubectl apply -f k8s/configmap.yaml
       kubectl apply -f k8s/secret.yaml
       kubectl apply -f k8s/deployment.yaml
       kubectl apply -f k8s/service.yaml
       kubectl apply -f k8s/ingress.yaml